title: "Sharmaji Blog"
baseurl: "/en/blog"
url: "https://gitesh-sharma.github.io/en"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
permalink: /:year/:month/:day/:title/
