
title: "Sharmaji Technology Media Blog"
tagline: "Latest tech posts & tutorials"
description: "A blog by Sharmaji Technology Media"
baseurl: "/en/blog"
url: "https://gitesh-sharma.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
