name: Build Blog

on:
  push:
    paths:
      - 'blog-src/**'
      - '.github/workflows/build-blog.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Dependencies
        run: |
          cd blog-src
          gem install bundler
          bundle install

      - name: Build Jekyll
        run: |
          cd blog-src
          bundle exec jekyll build --destination "../en/blog"

      - name: Commit blog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add en/blog
          git commit -m "Rebuild blog" || echo "No changes"
          git push
